In [3]:
# 변수선언 

a = 100
b = 'python is interesting.'
type(a), type(b)

(int, str)

In [4]:
a = 123
b = '40'

# 123+40 = 163
print(str(a) + b)
print(a + int(b))

12340
163


In [6]:
# 문자열 인덱싱(Indexing) & 슬라이싱(Slicing)

a = 'Hello my name is python.'
# Hello 슬라이싱 [포함:미포함] 
print(a[0:5])

Hello


In [7]:
b = 'banana'
# ananab
print(b[::-1])

ananab


In [8]:
c = 'APPLE'
# A 를 프린트하시오.
c[0]

'A'

In [11]:
import numpy as np

n = np.array([1,3,5,7,9])
# 5 인덱싱
print(n[2])
# 1, 5, 9 
print(n[::2])

5
[1 5 9]


In [12]:
colors = ['R','G','B']
for c in colors:
    print(c)

R
G
B


In [17]:
data = [['백지선', 10], ['강신덕', 20],['김윤우', 30]]

for i in data :
    for a in i :
        print(a, end = " ")
        print()
        

# 백지선 10
# 강신덕 20
# 김윤우 30 

백지선 
10 
강신덕 
20 
김윤우 
30 


In [18]:
data = [['백지선', 10], ['강신덕', 20],['김윤우', 30]]

for name, age in data:
    print(name, age)

백지선 10
강신덕 20
김윤우 30


In [20]:
# 함수
def add(x, y):
    return x + y

print(add(10,20))
print(add(y = 40, x = 10))

30
50


In [23]:
def example(*numbers):
    print(numbers)
    
    for n in numbers:
        print(n)
    
example(1, 2, 3, 4, 5, 6)

(1, 2, 3, 4, 5, 6)
1
2
3
4
5
6


In [24]:
def add_all(*nums):
    total = 0
    for n in nums:
        total += n
    return total

print(add_all(1,2,3,4,5))

15


In [27]:
import numpy as np

arr = np.arange(6)
print(arr)

arr = np.reshape(arr, (2,3))
print(arr)
print(arr.shape)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
(2, 3)


In [29]:
arr = np.arange(6)
print(arr)

arr = np.reshape(arr, (2,-1))
print(arr)
print(arr.shape)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
(2, 3)


In [30]:
print(arr)

[[0 1 2]
 [3 4 5]]


In [34]:
# numpy sum 결과를 -> [3,5,7]
arr.sum(axis = 0)

array([3, 5, 7])

In [35]:
# numpy sum 결과를 -> [3,12]
arr.sum(axis = 1)

array([ 3, 12])

In [36]:
import pandas as pd

# 1차원 -> Series
# 2차원 -> DataFrame 

# isnull() , isna()
# notnull(), notna()
# dropna how옵션 , how = 'all' -> 모든행이나 모든열이 다 NaN값일 때 삭제 , how = 'any' -> 1개라도 NaN값이 있으면 버려라.

In [37]:
# pandas excel, csv
# read_csv('')
# read_excel('')

In [38]:
print(arr)

[[0 1 2]
 [3 4 5]]


In [41]:
df = pd.DataFrame(arr)
display(df)

df.columns = list('abc')
df.index = list('가나')
df

0  1  2
0  0  1  2
1  3  4  5

a  b  c
가  0  1  2
나  3  4  5

In [42]:
list('abc')

['a', 'b', 'c']

In [46]:
# groupby, pivot_table 

data = [['2020', 10,20,30],['2020', 7,11,4],['2022', 9, 5, 8]]

df = pd.DataFrame(data, columns = ['연도', 'num1', 'num2', 'num3'])
display(df)

df.groupby('연도').sum()

연도  num1  num2  num3
0  2020    10    20    30
1  2020     7    11     4
2  2022     9     5     8

num1  num2  num3
연도                    
2020    17    31    34
2022     9     5     8

In [52]:
data = {
    'apple' :['a','b','a','b','a','b'],
    'banan' :[1,2,3,4,5,2],
    'mango' : [6,7,8,9,10,11]
       }

df2 = pd.DataFrame(data)
display(df2)

# pivot_table -> index = 'apple', columns = 'banan' 연산 평균

df2.pivot_table(index = 'apple', columns = 'banan', aggfunc = ['mean','sum'])

apple  banan  mango
0     a      1      6
1     b      2      7
2     a      3      8
3     b      4      9
4     a      5     10
5     b      2     11

mean                        sum                      
      mango                      mango                      
banan     1    2    3    4     5     1     2    3    4     5
apple                                                       
a       6.0  NaN  8.0  NaN  10.0   6.0   NaN  8.0  NaN  10.0
b       NaN  9.0  NaN  9.0   NaN   NaN  18.0  NaN  9.0   NaN

In [53]:
# ML
# 1. 데이터 불러오기
# 2. 데이터 분석해서 EDA 결측치 처리, 전처리
# 3. 데이터 분리(train_test_split)
# 4. 모델 학습 model.fit()
# 5. 평가 (model.score), model.predict 제출 

# 데이터 표준화 -> standardscaler()
# 데이터 정규화 -> minmaxscaler()

# 지도, 비지도 차이점 -> 정답의 유무 (라벨의 유무)

# 규제 (Regularization)
# - L1 (Lasso)
# - L2 (Ridge)

In [ ]:
# Ensemble

1. voting
2. bagging -> RandomForest
3. boosting
4. stacking 

In [55]:
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression

digits = load_digits()

X = digits['data']
Y = digits['target']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 0)
model = LogisticRegression().fit(x_train, y_train)

model.score(x_train, y_train), model.score(x_test, y_test)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


(1.0, 0.9537037037037037)