In [86]:
# 변수선언 

a = 100
b = 'python is interesting.'
type(a), type(b)

(int, str)

In [87]:
a = 123
b = '40'

# 123+40 = 163
print(str(a) + b)
print(a + int(b))

12340
163


In [88]:
# 문자열 인덱싱(Indexing) & 슬라이싱(Slicing)

a = 'Hello my name is python.'
# Hello 슬라이싱 [포함:미포함] 
print(a[0:5])

Hello


In [89]:
b = 'banana'
# ananab
print(b[::-1])

ananab


In [90]:
c = 'APPLE'
# A 를 프린트하시오.
c[0]

'A'

In [91]:
import numpy as np

n = np.array([1,3,5,7,9])
# 5 인덱싱
print(n[2])
# 1, 5, 9 
print(n[::2])

5
[1 5 9]


In [92]:
colors = ['R','G','B']
for c in colors:
    print(c)

R
G
B


In [93]:
data = [['백지선', 10], ['강신덕', 20],['김윤우', 30]]

for i in data :
    for a in i :
        print(a, end = " ")
        print()
        

# 백지선 10
# 강신덕 20
# 김윤우 30 

백지선 
10 
강신덕 
20 
김윤우 
30 


In [94]:
data = [['백지선', 10], ['강신덕', 20],['김윤우', 30]]

for name, age in data:
    print(name, age)

백지선 10
강신덕 20
김윤우 30


In [95]:
# 함수
def add(x, y):
    return x + y

print(add(10,20))
print(add(y = 40, x = 10))

30
50


In [96]:
def example(*numbers):
    print(numbers)
    
    for n in numbers:
        print(n)
    
example(1, 2, 3, 4, 5, 6)

(1, 2, 3, 4, 5, 6)
1
2
3
4
5
6


In [97]:
def add_all(*nums):
    total = 0
    for n in nums:
        total += n
    return total

print(add_all(1,2,3,4,5))

15


In [98]:
import numpy as np

arr = np.arange(6)
print(arr)

arr = np.reshape(arr, (2,3))
print(arr)
print(arr.shape)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
(2, 3)


In [99]:
arr = np.arange(6)
print(arr)

arr = np.reshape(arr, (2,-1))
print(arr)
print(arr.shape)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
(2, 3)


In [100]:
print(arr)

[[0 1 2]
 [3 4 5]]


In [101]:
# numpy sum 결과를 -> [3,5,7]
arr.sum(axis = 0)

array([3, 5, 7])

In [102]:
# numpy sum 결과를 -> [3,12]
arr.sum(axis = 1)

array([ 3, 12])

In [103]:
import pandas as pd

# 1차원 -> Series
# 2차원 -> DataFrame 

# isnull() , isna()
# notnull(), notna()
# dropna how옵션 , how = 'all' -> 모든행이나 모든열이 다 NaN값일 때 삭제 , how = 'any' -> 1개라도 NaN값이 있으면 버려라.

In [104]:
# pandas excel, csv
# read_csv('')
# read_excel('')

In [105]:
print(arr)

[[0 1 2]
 [3 4 5]]


In [106]:
df = pd.DataFrame(arr)
display(df)

df.columns = list('abc')
df.index = list('가나')
df

0  1  2
0  0  1  2
1  3  4  5

a  b  c
가  0  1  2
나  3  4  5

In [107]:
list('abc')

['a', 'b', 'c']

In [108]:
# groupby, pivot_table 

data = [['2020', 10,20,30],['2020', 7,11,4],['2022', 9, 5, 8]]

df = pd.DataFrame(data, columns = ['연도', 'num1', 'num2', 'num3'])
display(df)

df.groupby('연도').sum()

연도  num1  num2  num3
0  2020    10    20    30
1  2020     7    11     4
2  2022     9     5     8

num1  num2  num3
연도                    
2020    17    31    34
2022     9     5     8

In [109]:
data = {
    'apple' :['a','b','a','b','a','b'],
    'banana' :[1,2,3,4,5,2],
    'mango' : [6,7,8,9,10,11]
       }

df2 = pd.DataFrame(data)
display(df2)

# pivot_table -> index = 'apple', columns = 'banan' 연산 평균

df2.pivot_table(index = 'apple', columns = 'banana', aggfunc = ['mean','sum'])
#위 피봇테이블은 바나나와 애플간의 관계를 보여주는게 아니라 애플은 index로 하고 바나나를 칼럼으로 했을때 망고의 평균과 분산을 각각 테이블로 구성했다

apple  banana  mango
0     a       1      6
1     b       2      7
2     a       3      8
3     b       4      9
4     a       5     10
5     b       2     11

mean                        sum                      
       mango                      mango                      
banana     1    2    3    4     5     1     2    3    4     5
apple                                                        
a        6.0  NaN  8.0  NaN  10.0   6.0   NaN  8.0  NaN  10.0
b        NaN  9.0  NaN  9.0   NaN   NaN  18.0  NaN  9.0   NaN

In [110]:
# ML
# 1. 데이터 불러오기
# 2. 데이터 분석해서 EDA 결측치 처리, 전처리
# 3. 데이터 분리(train_test_split)
# 4. 모델 학습 model.fit()
# 5. 평가 (model.score), model.predict 제출 

# 데이터 표준화 -> standardscaler()
# 데이터 정규화 -> minmaxscaler()

# 지도, 비지도 차이점 -> 정답의 유무 (라벨의 유무)

# 규제 (Regularization)
# - L1 (Lasso)
# - L2 (Ridge)

In [111]:
# Ensemble

# 1. voting
# 2. bagging -> RandomForest
# 3. boosting
# 4. stacking 

In [112]:
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression

digits = load_digits()

X = digits['data']
Y = digits['target']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 0)
model = LogisticRegression().fit(x_train, y_train)

model.score(x_train, y_train), model.score(x_test, y_test)

/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


(1.0, 0.9537037037037037)

#마지막 테스트

In [113]:
data = [['Seoul', 11], ['Busan', 26], ['Daegu', 27], ['Incheon', 28]]
for name, code in data: 
    print(name, code)

Seoul 11
Busan 26
Daegu 27
Incheon 28


In [115]:
value = 123

print(str(value) + "km") 

123km


In [116]:
def add(a=3, b=5):
    return a+b
res = add(b=10, a=1)
print(res)

11


In [117]:
msg = 'mySUNI'
print(msg[::-1])

INUSym


In [119]:
apart = [ [101, 102], [201, 202], [301, 302] ]
for row in apart[::-1]:
    for col in row:

        print(col, "호")

301 호
302 호
201 호
202 호
101 호
102 호


In [120]:
def calc(*numbers):
    total = 0
    for n in numbers:
        total += n
    return total
res = calc(2, 4, 5)
print(res)

11


In [121]:
import numpy as np
array = np.array([[1,2,3], [4,5,6]])
print(array.sum(axis=0))

[5 7 9]


In [123]:
array = np.arange(6)
array.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
import pandas as pd
df = pd.read_excel('data.xlsx')

In [140]:
# [df구조]
#    A  B
# a  1  5
# b  2  6
# c  3  7
# d  4  8

# [출력결과]
# b    2
# c    3
# Name: A, dtype: int64
arr = np.arange(1,9)
arr = np.reshape(arr, (2,-1))
arr = arr.T
df = pd.DataFrame(arr)
df.columns = list('AB')
df.index = list('abcd')
display(df)

display(df.loc[(df['A']>1) & (df['A']<4), 'A'])

A  B
a  1  5
b  2  6
c  3  7
d  4  8

b    2
c    3
Name: A, dtype: int64

In [141]:
# groupby, pivot_table 

data = [['2020', 14,14,13],['2020', 14,12,18],['2021', 18, 13, 16],['2021', 12, 17, 15]]

df = pd.DataFrame(data, columns = ['연도', 'A', 'B', 'C'])
display(df)

df.groupby('연도').sum()

연도   A   B   C
0  2020  14  14  13
1  2020  14  12  18
2  2021  18  13  16
3  2021  12  17  15

A   B   C
연도              
2020  28  26  31
2021  30  30  31

In [143]:
data = {
        'A' : ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
        'B' : ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
        'C' : [7, 2, 6, 0, 9, 9, 9, 7],
        'D' : [8, 1, 5, 9, 1, 5, 7, 3],
}
df = pd.DataFrame(data)
df.pivot_table(index = 'A', columns = 'B', aggfunc = ['mean','sum'])

mean                            sum                        
       C               D              C             D          
B    one three  two  one three  two one three two one three two
A                                                              
bar  2.0   0.0  9.0  1.0   9.0  5.0   2     0   9   1     9   5
foo  8.0   7.0  7.5  7.5   3.0  3.0  16     7  15  15     3   6

In [144]:
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
digits = load_digits()
#-------------------------------

X = digits['data']
Y = digits['target']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 0)
model = LogisticRegression().fit(x_train, y_train)

model.score(x_train, y_train), model.score(x_test, y_test)


/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


(1.0, 0.9537037037037037)