# 계단오르내리기 예제

In [43]:
import numpy as np 
np.random.seed(888)

- randint 함수를 사용하여 1000개의 랜덤값 생성 (0=계단 내려감, 1=계단 올라감)

In [44]:
draws = np.random.randint(0,2,size=1000) 
draws

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,

- draws 값이 0인 경우 -1로 변경 후(숫자를 감소시키기 위해), steps 변수에 저장 (Hint: np.where)

In [45]:
steps = np.where(draws == 0, -1, draws)

In [46]:
steps

array([-1, -1,  1,  1, -1,  1,  1, -1,  1, -1,  1,  1, -1,  1, -1, -1,  1,
        1, -1, -1, -1,  1, -1, -1, -1, -1,  1, -1,  1,  1, -1, -1, -1,  1,
       -1, -1,  1,  1, -1, -1, -1, -1,  1,  1, -1, -1, -1, -1,  1,  1, -1,
        1,  1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1,  1, -1,  1,  1, -1,
       -1,  1,  1,  1, -1, -1,  1, -1, -1, -1,  1, -1,  1, -1, -1,  1, -1,
       -1, -1, -1,  1,  1,  1,  1, -1, -1,  1, -1,  1, -1, -1, -1,  1,  1,
        1, -1, -1,  1,  1, -1, -1,  1,  1, -1, -1, -1, -1,  1,  1, -1, -1,
       -1, -1,  1,  1, -1,  1, -1,  1, -1,  1, -1, -1, -1, -1,  1,  1,  1,
       -1,  1,  1, -1,  1,  1,  1,  1,  1, -1, -1,  1,  1,  1, -1,  1,  1,
        1,  1, -1,  1,  1,  1, -1, -1, -1, -1,  1, -1,  1,  1, -1, -1,  1,
       -1,  1, -1, -1,  1,  1, -1, -1, -1,  1,  1, -1,  1, -1, -1, -1, -1,
        1, -1, -1, -1,  1, -1,  1, -1, -1, -1,  1, -1, -1,  1, -1,  1,  1,
       -1,  1, -1, -1,  1, -1,  1,  1, -1, -1,  1,  1,  1, -1, -1,  1, -1,
       -1,  1,  1, -1,  1

- steps 배열의 누적합(cumsum) 계산 후 walk 변수에 저장(계단을 오르 내린 누적합)

In [47]:
walk = np.cumsum(steps)

In [48]:
walk

array([ -1,  -2,  -1,   0,  -1,   0,   1,   0,   1,   0,   1,   2,   1,
         2,   1,   0,   1,   2,   1,   0,  -1,   0,  -1,  -2,  -3,  -4,
        -3,  -4,  -3,  -2,  -3,  -4,  -5,  -4,  -5,  -6,  -5,  -4,  -5,
        -6,  -7,  -8,  -7,  -6,  -7,  -8,  -9, -10,  -9,  -8,  -9,  -8,
        -7,  -8,  -9, -10, -11, -10, -11, -12, -13, -14, -15, -14, -15,
       -14, -13, -14, -15, -14, -13, -12, -13, -14, -13, -14, -15, -16,
       -15, -16, -15, -16, -17, -16, -17, -18, -19, -20, -19, -18, -17,
       -16, -17, -18, -17, -18, -17, -18, -19, -20, -19, -18, -17, -18,
       -19, -18, -17, -18, -19, -18, -17, -18, -19, -20, -21, -20, -19,
       -20, -21, -22, -23, -22, -21, -22, -21, -22, -21, -22, -21, -22,
       -23, -24, -25, -24, -23, -22, -23, -22, -21, -22, -21, -20, -19,
       -18, -17, -18, -19, -18, -17, -16, -17, -16, -15, -14, -13, -14,
       -13, -12, -11, -12, -13, -14, -15, -14, -15, -14, -13, -14, -15,
       -14, -15, -14, -15, -16, -15, -14, -15, -16, -17, -16, -1

- walk의 최소값 

In [49]:
np.min(walk)

-36

- walk의 최대값

In [50]:
np.max(walk)

2

# 계단의 처음 위치에서 10칸(위, 아래) 이상 떨어진 지점 구하기

- walk 배열의 음수를 양수로 변경(Hint:np.abs)

In [51]:
walk = np.abs(walk)

In [52]:
walk

array([ 1,  2,  1,  0,  1,  0,  1,  0,  1,  0,  1,  2,  1,  2,  1,  0,  1,
        2,  1,  0,  1,  0,  1,  2,  3,  4,  3,  4,  3,  2,  3,  4,  5,  4,
        5,  6,  5,  4,  5,  6,  7,  8,  7,  6,  7,  8,  9, 10,  9,  8,  9,
        8,  7,  8,  9, 10, 11, 10, 11, 12, 13, 14, 15, 14, 15, 14, 13, 14,
       15, 14, 13, 12, 13, 14, 13, 14, 15, 16, 15, 16, 15, 16, 17, 16, 17,
       18, 19, 20, 19, 18, 17, 16, 17, 18, 17, 18, 17, 18, 19, 20, 19, 18,
       17, 18, 19, 18, 17, 18, 19, 18, 17, 18, 19, 20, 21, 20, 19, 20, 21,
       22, 23, 22, 21, 22, 21, 22, 21, 22, 21, 22, 23, 24, 25, 24, 23, 22,
       23, 22, 21, 22, 21, 20, 19, 18, 17, 18, 19, 18, 17, 16, 17, 16, 15,
       14, 13, 14, 13, 12, 11, 12, 13, 14, 15, 14, 15, 14, 13, 14, 15, 14,
       15, 14, 15, 16, 15, 14, 15, 16, 17, 16, 15, 16, 15, 16, 17, 18, 19,
       18, 19, 20, 21, 20, 21, 20, 21, 22, 23, 22, 23, 24, 23, 24, 23, 22,
       23, 22, 23, 24, 23, 24, 23, 22, 23, 24, 23, 22, 21, 22, 23, 22, 23,
       24, 23, 22, 23, 22

- walk 배열의 값이 10 이상인 경우 True, 아닌 경우 False로 변경 

In [53]:
np.where(walk >= 10, True, False)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

- argmax 함수를 이용해 최댓값을 조회 -> 중복값이 존재한다면 첫번째 인덱스를 반환

In [54]:
np.argmax(walk)

421