In [4]:
val = 'python'

In [5]:
val

'python'

In [6]:
val[0]

'p'

In [7]:
val[1:4]

'yth'

In [8]:
str = '210101-1234567'

In [9]:
str

'210101-1234567'

In [10]:
str[7]

'1'

In [11]:
str1 = '20210101Sunny'

In [12]:
str1

'20210101Sunny'

In [13]:
date = str1[0:8]
weather = str1[8:]

In [15]:
date

'20210101'

In [16]:
weather

'Sunny'

In [17]:
len(weather)

5

In [19]:
val = ','.join(weather)

In [20]:
val

'S,u,n,n,y'

In [22]:
val.split(',')

['S', 'u', 'n', 'n', 'y']

In [24]:
score = input("enter score")

enter score99


In [25]:
type(score)

str

In [26]:
score

'99'

In [27]:
id(score)

140061037117880

In [28]:
a='11223445672'

In [29]:
a

'11223445672'

In [30]:
a_set=set(a)

In [31]:
a_set

{'1', '2', '3', '4', '5', '6', '7'}

In [48]:
b = list(a_set)

In [49]:
b

['1', '7', '5', '3', '6', '4', '2']

In [54]:
b.sort(reverse=True)

In [55]:
b

['7', '6', '5', '4', '3', '2', '1']

In [58]:
# (몸무게 + 100 - 키) => 비만수치공식

키 = input("키: ")
몸무게 = input("몸무게: ")

비만수치 = (int(몸무게) + 100 - int(키))
if 비만수치 > 0:
    print("당신은 비만입니다")
else:
    print("당신은 비만이 아닙니다")

키: 172
몸무게: 87
당신은 비만입니다


In [4]:
str = "*"
i = 0
while i < 5:
    print(str)
    str += "*"
    i += 1

*
**
***
****
*****


In [2]:
# 결과 : 1 2 3 4 5 6 7 8 9 10 
test2D = [[1,2,3],[4,5,6],[7,8,9,10]]
for i in test2D:
    for j in i:
        print(j, end=" ")

1 2 3 4 5 6 7 8 9 10 

In [4]:
def printInfo(**args):
    print(args)
dict = {'aa':3, 'bb':4}
printInfo(**dict)

{'aa': 3, 'bb': 4}


In [2]:
import numpy as np

In [7]:
np_array = np.ones((2,2))

In [9]:
np_array.shape

(2, 2)

In [10]:
np_array.size

4

In [11]:
np_array.dtype

dtype('float64')

In [12]:
np_array.ndim

2

In [13]:
bidx = np_array % 2 == 0

In [14]:
bidx

array([[False, False],
       [False, False]])

In [17]:
np_array[bidx]

array([], dtype=float64)

In [3]:
x = np.array([[0,1,2], [3,4,5], [6,7,8]])

In [4]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
x[0, :]

array([0, 1, 2])

In [6]:
x[:,1]

array([1, 4, 7])

In [27]:
x[:2,1:]

array([[1, 2],
       [4, 5]])

In [28]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
np.where(x % 2 == 0)

(array([0, 0, 1, 2, 2]), array([0, 2, 1, 0, 2]))

In [30]:
x[x%2 == 0]

array([0, 2, 4, 6, 8])

In [8]:
total = 0
for num in range(4, 10, 2):
    if num % 3 == 0: 
        break
    total = total + num

print(total)

4


In [9]:
hotel = [[101, 102], [201, 202], [301, 302]]
for floor in hotel:
    for room in floor:
        print(room, end=" ") 

    print()

101 102 
201 202 
301 302 


In [13]:
import numpy as np
array = np.arange(1,10).reshape(-1, 3)
print(array.sum(axis=1))

[ 6 15 24]


In [12]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])