In [1]:
from IPython.core.display import display, HTML
display(HTML(
"""<style>
div.container { width:100% !important; }
div.CodeMirror {font-family: Consolas; font-size: 17pt;}
div.output { font-weight: bold; font-size: 17pt;}
div.input { font-family: Consolas; font-size: 17pt;}
div.prompt { min-width: 100px;}
</style>
"""))

# 연습문제

In [8]:
# 일반 for문
list_result = []
for x in range(10):
    print(x**2)

0
1
4
9
16
25
36
49
64
81


In [11]:
# list comprehension
list_result2 = [x**2 for x in range(10)]
type(list_result2)

list

In [13]:
num1, num2 = (3,4)
print('num1=',num1, 'num2=',num2)

num1= 3 num2= 4


In [ ]:
start=0
end, start = (10, 2)

In [14]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

# Numpy

In [16]:
import numpy as np
#np.where(조건 [,X, Y])
array = np.arange(9).reshape(3, -1)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.where(array % 2 == 0)

(array([0, 0, 1, 2, 2]), array([0, 2, 1, 0, 2]))

In [15]:
np.where(array % 2 == 0, 100, array)

array([[100,   1, 100],
       [  3, 100,   5],
       [100,   7, 100]])

In [18]:
import numpy as np
#np.where(조건 [,X, Y])
array = np.arange(9).reshape(3, -1)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
#axis에 따른 연산 결과
display(array.sum()) # axis=None
display(array.sum(axis=0)) # axis=0 행끼리 더해라/포개라
display(array.sum(axis=1)) # axis=1 열끼리 더해라/포개라

36

array([ 9, 12, 15])

array([ 3, 12, 21])