In [17]:
from IPython.core.display import display, HTML
display(HTML(
"""<style>
div.container { width:100% !important; }
div.CodeMirror {font-family: Consolas; font-size: 17pt;}
div.output { font-weight: bold; font-size: 17pt;}
div.input { font-family: Consolas; font-size: 17pt;}
div.prompt { min-width: 100px;}
</style>
"""))

# 연습문제

In [18]:
# 일반 for문
list_result = []
for x in range(10):
    print(x**2)

0
1
4
9
16
25
36
49
64
81


In [19]:
# list comprehension
list_result2 = [x**2 for x in range(10)]
type(list_result2)

list

In [20]:
num1, num2 = (3,4)
print('num1=',num1, 'num2=',num2)

num1= 3 num2= 4


In [21]:
start=0
end, start = (10, 2)

In [22]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

# Numpy

In [23]:
import numpy as np
#np.where(조건 [,X, Y])
array = np.arange(9).reshape(3, -1)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
np.where(array % 2 == 0)

(array([0, 0, 1, 2, 2]), array([0, 2, 1, 0, 2]))

In [25]:
np.where(array % 2 == 0, 100, array)

array([[100,   1, 100],
       [  3, 100,   5],
       [100,   7, 100]])

In [26]:
import numpy as np
#np.where(조건 [,X, Y])
array = np.arange(9).reshape(3, -1)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
#axis에 따른 연산 결과
display(array.sum()) # axis=None
display(array.sum(axis=0)) # axis=0 행끼리 더해라/포개라
display(array.sum(axis=1)) # axis=1 열끼리 더해라/포개라

36

array([ 9, 12, 15])

array([ 3, 12, 21])

In [28]:
import pandas as pd
data = list('python')

In [29]:
data

['p', 'y', 't', 'h', 'o', 'n']

In [30]:
s = pd.Series(data, index=['idx0', 'idx1', 'idx2', 'idx3', 'idx4', 'idx5'])

In [31]:
s

idx0    p
idx1    y
idx2    t
idx3    h
idx4    o
idx5    n
dtype: object

In [32]:
s.shape

(6,)

In [33]:
s.values

array(['p', 'y', 't', 'h', 'o', 'n'], dtype=object)

In [34]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

In [35]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [43]:
data_dict = {
    'name': ['K', 'L', 'P'],
    'age' : [24, 27, 34],
    'children' : [2,1,3]
}

In [45]:
df = pd.DataFrame(data_dict)

In [46]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [47]:
df.columns

Index(['name', 'age', 'children'], dtype='object')

In [48]:
df['name']

0    K
1    L
2    P
Name: name, dtype: object