In [1]:
import numpy as np
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [2]:
np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.array([[[ 0,  1,  2,  3],
           [ 4,  5,  6,  7],
           [ 8,  9, 10, 11]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0.1, 1.1, 0.1)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [6]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [7]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [8]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [9]:
np.full((2,2), -1)

array([[-1, -1],
       [-1, -1]])

In [10]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [11]:
array = np.array([[1, 2], [3, 4]])
print('array의 차원:', array.ndim)

array의 차원: 2


In [12]:
print('array의 각 차원별 크기:', array.shape)

array의 각 차원별 크기: (2, 2)


In [13]:
print('array의 요소의 총 개수 :', array.size)

array의 요소의 총 개수 : 4


In [14]:
print('array의 데이터 유형 :', array.dtype)

array의 데이터 유형 : int32


In [15]:
print('array의 전치 (전) :')
print(array)
print('array의 전치 (후) :')
print(array.T)

array의 전치 (전) :
[[1 2]
 [3 4]]
array의 전치 (후) :
[[1 3]
 [2 4]]


In [16]:
array = np.arange(16)
array, array.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 (16,))

In [17]:
array.reshape(4, 4), array.reshape(4, 4).shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 (4, 4))

In [18]:
x = np.array([[1,2], [3,4]])
x, x.dtype

(array([[1, 2],
        [3, 4]]),
 dtype('int32'))

In [19]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
x, x.dtype

(array([[1., 2.],
        [3., 4.]]),
 dtype('float64'))

In [20]:
x.astype(np.int32)

array([[1, 2],
       [3, 4]])

In [21]:
np.int32(x)

array([[1, 2],
       [3, 4]])

In [22]:
x.astype('int')

array([[1, 2],
       [3, 4]])

In [23]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

In [24]:
print(x + y)
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [25]:
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [26]:
print(x * y)
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [27]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [28]:
print(x @ y)
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [29]:
print(np.sqrt(x))
print(np.matmul(x, y))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[19 22]
 [43 50]]


In [30]:
print(x+1)

[[2 3]
 [4 5]]


In [31]:
print(x-1)

[[0 1]
 [2 3]]


In [32]:
print(x*2)

[[2 4]
 [6 8]]


In [33]:
print(x/2)

[[0.5 1. ]
 [1.5 2. ]]


In [34]:
x % 2 

array([[1, 0],
       [1, 0]], dtype=int32)

In [35]:
array = np.arange(9).reshape(3, 3)
array[0]

array([0, 1, 2])

In [36]:
array[-1]

array([6, 7, 8])

In [37]:
array[0, 0]

0

In [38]:
array[-1, -1]

8

In [39]:
bidx = array % 2 == 0
bidx

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [40]:
array[bidx]

array([0, 2, 4, 6, 8])

In [41]:
array[array > 5]

array([6, 7, 8])

In [42]:
row = [0, 1]
col = [2, 1]
array[row, col]

array([2, 4])

In [43]:
array[[0,1], [2, 1]]

array([2, 4])

In [44]:
array[0, 2], array[1, 1]

(2, 4)

In [45]:
array[0, :]

array([0, 1, 2])

In [46]:
array[:, 1]

array([1, 4, 7])

In [47]:
array[:2, 1:]

array([[1, 2],
       [4, 5]])

In [48]:
array[-1:, 1:3]

array([[7, 8]])

In [49]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
b = array[:, 1]
b

array([1, 4, 7])

In [51]:
b[0] = 10

In [52]:
array

array([[ 0, 10,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [53]:
b = array[:, 1].copy()
b

array([10,  4,  7])

In [54]:
b[0] = 1

In [55]:
array

array([[ 0, 10,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [56]:
np.where(array % 2 == 0)

(array([0, 0, 0, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 1, 0, 2], dtype=int64))

In [57]:
np.where(array % 2 == 0, True, False)

array([[ True,  True,  True],
       [False,  True, False],
       [ True, False,  True]])

In [58]:
array

array([[ 0, 10,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [59]:
array.sum()

45

In [60]:
array.sum(axis=0)

array([ 9, 21, 15])

In [61]:
array.sum(axis=1)

array([12, 12, 21])

In [62]:
np.save('array.npy', array)

In [63]:
new_array = np.load('array.npy')
new_array

array([[ 0, 10,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])